### ISSUE TITLE
Unable to start after git clone today.

### ISSUE THREAD

**Issue by Justinzobel** [flyingrhinonz/nccm#5]
```
./nccm/nccm 
Traceback (most recent call last):
  File "./nccm/nccm", line 1876, in <module>
    main()
  File "./nccm/nccm", line 1845, in main
    CommandLine = curses.wrapper(MainCursesFunction)
  File "/usr/lib/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "./nccm/nccm", line 1525, in MainCursesFunction
    ConnectionsList, ConnBox, FilterBox, CyclicTextboxObjects = SetupWindows(stdscr)
  File "./nccm/nccm", line 1494, in SetupWindows
    ConnectionsList.Load()
  File "./nccm/nccm", line 940, in Load
    LogWrite.debug('ImportNccmD = {} - not attempting to import connection details '
AttributeError: 'str' object has no attribute 'formaat'
```

**Comment by Justinzobel** [comment]
Appears to just be that spelling mistake in the word format. I fixed that in my local code and it worked.

**Comment by flyingrhinonz** [comment]
Thanks for pointing this out. Fixed and will push soon.
